version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
