version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile/dev.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./secrets/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - ./secrets/.env
    ports:
      - "3306:3306"
    volumes:
      - ~/data:/var/lib/mysql

volumes:
  mysql_data:
